(()=>{
  const config=window.FIDEST_ADMIN_CHAT||{}, items=[...document.querySelectorAll('.conversation-item')], messages=document.getElementById('adminChatMessages'), form=document.getElementById('adminChatForm'), input=document.getElementById('adminChatInput'), file=document.getElementById('adminChatFile'), status=document.getElementById('adminFileStatus'), attach=document.getElementById('adminAttach'), head=document.getElementById('adminChatHead');let current=0;
  if(!form)return;file.multiple=true;let renderedConversation=0,lastSignature='',lastMessageCount=0;const down=document.createElement('button');down.type='button';down.className='admin-chat-down';down.title='Voir les nouveaux messages';down.innerHTML='<i class="fa-solid fa-arrow-down"></i><b></b>';form.parentElement.appendChild(down);const hideDown=()=>down.classList.remove('show');down.addEventListener('click',()=>{messages.scrollTo({top:messages.scrollHeight,behavior:'smooth'});hideDown();});messages.addEventListener('scroll',()=>{if(messages.scrollHeight-messages.scrollTop-messages.clientHeight<90)hideDown();},{passive:true});
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const headIdentity=document.createElement('div');headIdentity.className='admin-chat-identity';headIdentity.append(head.querySelector('strong'),head.querySelector('small'));head.prepend(headIdentity);const contactPanel=document.createElement('div');contactPanel.className='admin-contact-panel';head.appendChild(contactPanel);
  const renderContact=visitor=>{if(!visitor){contactPanel.innerHTML='';return;}const phone=visitor.telephone_visiteur||'',whatsapp=visitor.whatsapp_visiteur||'',pending=visitor.contact_request||'';contactPanel.innerHTML=`<div class="admin-contact-info"><span><i class="fa-regular fa-envelope"></i>${esc(visitor.email_visiteur||'E-mail non renseigné')}</span><span><i class="fa-solid fa-phone"></i>${phone?`<a href="tel:${esc(phone)}">${esc(phone)}</a>`:'Non renseigné'}</span><span><i class="fa-brands fa-whatsapp"></i>${whatsapp?`<a href="https://wa.me/${esc(whatsapp.replace(/\D/g,''))}" target="_blank" rel="noopener">${esc(whatsapp)}</a>`:'Non renseigné'}</span></div><div class="admin-contact-actions"><button type="button" data-contact="telephone" ${pending?'disabled':''}><i class="fa-solid fa-phone"></i>${pending==='telephone'?'Téléphone demandé':'Demander téléphone'}</button><button type="button" data-contact="whatsapp" ${pending?'disabled':''}><i class="fa-brands fa-whatsapp"></i>${pending==='whatsapp'?'WhatsApp demandé':'Demander WhatsApp'}</button></div>`;};
  const summary=()=>{const files=[...file.files];if(!files.length)return'';const size=files.reduce((n,item)=>n+item.size,0);return `${files.length} fichier${files.length>1?'s':''} sélectionné${files.length>1?'s':''} · ${(size/1048576).toFixed(size>=1048576?1:2)} Mo`;};
  const attachment=m=>{if(!m.fichier)return'';const href=esc(m.fichier),name=esc(m.fichier_original||'Fichier joint');if(String(m.mime_type||'').startsWith('image/'))return `<a class="admin-attachment-image" href="${href}" target="_blank" rel="noopener"><img src="${href}" alt="${name}" loading="lazy"></a>`;return `<a class="admin-attachment-file" href="${href}" target="_blank" rel="noopener" download><i class="fa-solid fa-file-arrow-down"></i><span>${name}<small>Télécharger</small></span></a>`;};
  const render=(list,forceBottom=false)=>{const signature=list.map(m=>`${m.id}:${m.message}:${m.fichier}`).join('|');if(renderedConversation===current&&signature===lastSignature)return;const wasNearBottom=messages.scrollHeight-messages.scrollTop-messages.clientHeight<90,newCount=renderedConversation===current?Math.max(0,list.length-lastMessageCount):0,previousTop=messages.scrollTop;messages.innerHTML=list.map(m=>{const admin=m.expediteur==='utilisateur',avatar=admin?`<img class="admin-agent-avatar" src="${esc(m.agent_photo||'images/default-avatar.svg')}" alt="">`:'';const sender=admin?`<div class="admin-sender">${esc(m.agent||'Conseiller FIDEST')}<small>${esc(m.agent_fonction||'Service client')}</small></div>`:'';return `<div class="admin-message-row ${esc(m.expediteur)}"><div>${sender}<div class="admin-message ${esc(m.expediteur)}">${m.message?`<div>${esc(m.message).replace(/\n/g,'<br>')}</div>`:''}${attachment(m)}<small>${esc(m.created_at||'')}</small></div></div>${avatar}</div>`;}).join('')||'<div class="chat-placeholder">Aucun message.</div>';renderedConversation=current;lastSignature=signature;lastMessageCount=list.length;if(forceBottom||wasNearBottom){messages.scrollTop=messages.scrollHeight;hideDown();}else{messages.scrollTop=previousTop;if(newCount){down.querySelector('b').textContent=String(newCount);down.classList.add('show');}}};
  const load=async(forceBottom=false)=>{if(!current)return;try{const response=await fetch(`request/chat_admin.php?conversation_id=${current}&_=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/json'}}),data=await response.json();renderContact(data.visitor);render(data.messages||[],forceBottom);}catch(e){}};
  const select=item=>{current=Number(item.dataset.conversation);renderedConversation=0;lastSignature='';lastMessageCount=0;hideDown();items.forEach(other=>other.classList.toggle('active',other===item));document.getElementById('adminChatName').textContent=item.dataset.name;document.getElementById('adminChatProduct').textContent=item.dataset.product;head.hidden=false;form.hidden=false;load(true);};
  items.forEach(item=>item.addEventListener('click',()=>select(item)));attach.addEventListener('click',()=>file.click());file.addEventListener('change',()=>status.textContent=summary());status.addEventListener('click',()=>{file.value='';status.textContent='';});
  contactPanel.addEventListener('click',async event=>{const button=event.target.closest('[data-contact]');if(!button||!current)return;button.disabled=true;const data=new FormData();data.append('csrf',config.csrf||'');data.append('conversation_id',String(current));data.append('action','request_contact');data.append('contact_type',button.dataset.contact);try{const response=await fetch('request/chat_admin.php',{method:'POST',body:data}),result=await response.json();if(result.error)throw new Error(result.error);await load(true);}catch(error){alert(error.message||'Demande impossible.');button.disabled=false;}});
  form.addEventListener('submit',async event=>{event.preventDefault();if(!current||(!input.value.trim()&&!file.files.length))return;const data=new FormData();data.append('csrf',config.csrf||'');data.append('conversation_id',String(current));data.append('message',input.value.trim());[...file.files].forEach(item=>data.append('files[]',item));const button=form.querySelector('.admin-send');button.disabled=true;try{const response=await fetch('request/chat_admin.php',{method:'POST',body:data}),result=await response.json();if(result.error)throw new Error(result.error);input.value='';file.value='';status.textContent='';await load(true);}catch(error){alert(error.message||'Envoi impossible.');}finally{button.disabled=false;}});
  const requested=items.find(item=>Number(item.dataset.conversation)===Number(config.requested));if(requested)select(requested);setInterval(load,3000);
})();
