(()=>{
  const $=id=>document.getElementById(id), box=$('publicChat'), trigger=$('publicChatTrigger'), close=$('closePublicChat'), messages=$('publicChatMessages'), form=$('publicChatForm'), input=$('chatMessage'), file=$('publicChatFile'), attach=$('publicChatAttach'), status=$('publicChatFileStatus');
  if(!box||!form)return;let lastSignature='',lastMessageCount=0;const down=document.createElement('button'),downStyle=document.createElement('style');downStyle.textContent='.public-chat-down{position:absolute;z-index:4;right:18px;bottom:112px;display:grid;width:42px;height:42px;place-items:center;color:#fff;background:#22254b;border:2px solid #fff;border-radius:50%;box-shadow:0 8px 22px #22254b4a;opacity:0;pointer-events:none;transform:translateY(10px) scale(.85);transition:.2s}.public-chat-down.show{opacity:1;pointer-events:auto;transform:none}.public-chat-down b{position:absolute;top:-5px;right:-4px;display:grid;min-width:19px;height:19px;padding:0 4px;place-items:center;color:#22254b;background:#fabd02;border:2px solid #fff;border-radius:11px;font-size:.55rem}';document.head.appendChild(downStyle);down.type='button';down.className='public-chat-down';down.title='Voir les nouveaux messages';down.innerHTML='<i class="fa-solid fa-arrow-down"></i><b></b>';box.appendChild(down);const hideDown=()=>down.classList.remove('show');down.addEventListener('click',()=>{messages.scrollTo({top:messages.scrollHeight,behavior:'smooth'});hideDown();});messages.addEventListener('scroll',()=>{if(messages.scrollHeight-messages.scrollTop-messages.clientHeight<70)hideDown();},{passive:true});
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const contactPrompt=document.createElement('div'),contactStyle=document.createElement('style');contactPrompt.className='chat-contact-request';contactStyle.textContent='.chat-contact-request{display:none;margin:0 0 9px;padding:11px;background:#fff7d9;border:1px solid #f0d272;border-radius:11px}.chat-contact-request.show{display:block}.chat-contact-request strong,.chat-contact-request small{display:block;color:#22254b}.chat-contact-request small{margin:3px 0 8px;color:#777b8d;font-size:.62rem}.chat-contact-fields{display:grid;grid-template-columns:1fr 38px;gap:6px}.chat-contact-fields input{min-width:0;padding:8px;border:1px solid #d9c36d;border-radius:8px;font-size:.72rem}.chat-contact-fields button{color:#fff;background:#22254b;border:0;border-radius:8px}';document.head.appendChild(contactStyle);form.insertBefore(contactPrompt,form.querySelector('.chat-compose'));
  const renderContactPrompt=visitor=>{const type=visitor?.contact_request||'';if(!type){contactPrompt.dataset.type='';contactPrompt.classList.remove('show');contactPrompt.innerHTML='';return;}if(contactPrompt.dataset.type===type)return;const whatsapp=type==='whatsapp',icon=whatsapp?'fa-brands fa-whatsapp':'fa-solid fa-phone';contactPrompt.dataset.type=type;contactPrompt.innerHTML=`<strong><i class="${icon}"></i> Votre conseiller demande votre numéro ${whatsapp?'WhatsApp':'de téléphone'}</strong><small>Il restera associé uniquement à cette conversation.</small><div class="chat-contact-fields"><input type="tel" inputmode="tel" autocomplete="tel" placeholder="Ex. +225 07 00 00 00 00"><button type="button" title="Transmettre mon numéro"><i class="fa-solid fa-check"></i></button></div>`;contactPrompt.classList.add('show');};
  const fileSummary=()=>{const files=[...file.files];if(!files.length)return'';const size=files.reduce((n,item)=>n+item.size,0);return `${files.length} fichier${files.length>1?'s':''} sélectionné${files.length>1?'s':''} · ${(size/1048576).toFixed(size>=1048576?1:2)} Mo`;};
  const attachment=m=>{if(!m.fichier)return'';const href=esc(m.fichier), name=esc(m.fichier_original||'Fichier joint');if(String(m.mime_type||'').startsWith('image/'))return `<a class="chat-attachment-image" href="${href}" target="_blank" rel="noopener"><img src="${href}" alt="${name}" loading="lazy"></a>`;return `<a class="chat-attachment-file" href="${href}" target="_blank" rel="noopener" download><i class="fa-solid fa-file-arrow-down"></i><span>${name}<small>Télécharger</small></span></a>`;};
  const render=(list,forceBottom=false)=>{if(!list.length)return;const signature=list.map(m=>`${m.id}:${m.message}:${m.fichier}`).join('|');if(signature===lastSignature)return;const wasNearBottom=messages.scrollHeight-messages.scrollTop-messages.clientHeight<70,newCount=Math.max(0,list.length-lastMessageCount),previousTop=messages.scrollTop;messages.innerHTML=list.map(m=>{const admin=m.expediteur==='utilisateur', avatar=admin?`<img class="chat-agent-avatar" src="${esc(m.agent_photo||'images/default-avatar.svg')}" alt="">`:'';const sender=admin?`<div class="chat-sender">${esc(m.agent||'Conseiller FIDEST')}<small>${esc(m.agent_fonction||'Service client')}</small></div>`:'';return `<div class="chat-row ${esc(m.expediteur)}">${avatar}<div>${sender}<div class="chat-message ${esc(m.expediteur)}">${m.message?`<div>${esc(m.message).replace(/\n/g,'<br>')}</div>`:''}${attachment(m)}<small>${esc(m.created_at||'')}</small></div></div></div>`;}).join('');lastSignature=signature;lastMessageCount=list.length;if(forceBottom||wasNearBottom){messages.scrollTop=messages.scrollHeight;hideDown();}else{messages.scrollTop=previousTop;if(newCount){down.querySelector('b').textContent=String(newCount);down.classList.add('show');}}};
  const lockIdentity=visitor=>{if(!visitor?.created)return;const name=$('chatName'),email=$('chatEmail');name.value=visitor.name||name.value;email.value=visitor.email||email.value;[name,email].forEach(field=>{field.readOnly=true;field.title='Identité enregistrée pour cette conversation';field.style.cssText='color:#777b8d;background:#ececf1;border-color:#d6d7df;cursor:not-allowed;box-shadow:inset 0 0 0 1px #ffffff80';});};
  const load=async(forceBottom=false)=>{try{const response=await fetch(`request/chat_public.php?_=${Date.now()}`,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}}),data=await response.json();lockIdentity(data.visitor);renderContactPrompt(data.visitor);render(data.messages||[],forceBottom);}catch(e){}};
  trigger?.addEventListener('click',()=>{box.classList.add('open');load(true);});close?.addEventListener('click',()=>box.classList.remove('open'));attach?.addEventListener('click',()=>file.click());file?.addEventListener('change',()=>status.textContent=fileSummary());status?.addEventListener('click',()=>{file.value='';status.textContent='';});
  contactPrompt.addEventListener('click',async event=>{const button=event.target.closest('button'),phone=contactPrompt.querySelector('input');if(!button||!phone)return;const data=new FormData();data.append('csrf',$('publicChatCsrf').value);data.append('action','save_contact');data.append('phone',phone.value.trim());button.disabled=true;try{const response=await fetch('request/chat_public.php',{method:'POST',body:data,credentials:'same-origin',cache:'no-store'}),result=await response.json();if(result.error)throw new Error(result.error);await load(true);}catch(error){alert(error.message||'Envoi impossible.');button.disabled=false;}});
  form.addEventListener('submit',async event=>{event.preventDefault();if(!input.value.trim()&&!file.files.length)return;const data=new FormData();data.append('csrf',$('publicChatCsrf').value);data.append('message',input.value.trim());data.append('name',$('chatName').value.trim());data.append('email',$('chatEmail').value.trim());data.append('product_id',$('publicChatProduct').value);[...file.files].forEach(item=>data.append('files[]',item));const button=form.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch('request/chat_public.php',{method:'POST',body:data,credentials:'same-origin',cache:'no-store'}),result=await response.json();if(result.error)throw new Error(result.error);input.value='';file.value='';status.textContent='';await load(true);}catch(error){alert(error.message||'Envoi impossible.');}finally{button.disabled=false;}});
  setInterval(()=>{if(box.classList.contains('open'))load();},3000);
})();
