document.addEventListener('DOMContentLoaded',()=>{
  const storageKey='fidest_public_cart';let cart=[];try{cart=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch(e){cart=[]}
  const money=value=>new Intl.NumberFormat('fr-FR').format(value)+' FCFA';
  const mobileNav=document.getElementById('mobileNav'),mobileNavBackdrop=document.getElementById('mobileNavBackdrop');
  const openMobileNav=()=>{mobileNav.classList.add('open');mobileNavBackdrop.classList.add('open');document.body.style.overflow='hidden'};
  const closeMobileNav=()=>{mobileNav.classList.remove('open');mobileNavBackdrop.classList.remove('open');document.body.style.overflow=''};
  document.getElementById('openMobileMenu').onclick=openMobileNav;document.getElementById('closeMobileMenu').onclick=closeMobileNav;mobileNavBackdrop.onclick=closeMobileNav;mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMobileNav));
  const drawer=document.getElementById('cartDrawer'),backdrop=document.getElementById('cartBackdrop'),lines=document.getElementById('cartLines'),empty=document.getElementById('cartEmpty'),summary=document.getElementById('cartSummary');
  const save=()=>{localStorage.setItem(storageKey,JSON.stringify(cart));renderCart()};
  const openCart=()=>{drawer.classList.add('open');backdrop.classList.add('open');document.body.style.overflow='hidden'};
  const closeCart=()=>{drawer.classList.remove('open');backdrop.classList.remove('open');document.body.style.overflow=''};
  function renderCart(){const count=cart.reduce((sum,line)=>sum+line.quantity,0),total=cart.reduce((sum,line)=>sum+line.price*line.quantity,0);document.getElementById('cartCount').textContent=count;document.getElementById('drawerCartCount').textContent=count;document.getElementById('cartHeaderTotal').textContent=money(total);document.getElementById('cartTotal').textContent=money(total);empty.hidden=cart.length>0;summary.hidden=cart.length===0;lines.innerHTML='';cart.forEach(line=>{const article=document.createElement('article');article.className='cart-line';article.innerHTML=line.image?`<img src="${escapeHtml(line.image)}" alt="">`:'<span class="cart-line__image"><i class="fa-solid fa-box"></i></span>';const content=document.createElement('div');content.innerHTML=`<h3>${escapeHtml(line.name)}</h3><small>${line.price?money(line.price)+' HT':'Prix sur devis'}</small><div class="quantity-control"><button type="button" data-change="-1">−</button><input value="${line.quantity}" readonly><button type="button" data-change="1">+</button></div>`;content.querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>{line.quantity=Math.max(1,line.quantity+Number(button.dataset.change));save()});const remove=document.createElement('button');remove.className='remove-line';remove.innerHTML='<i class="fa-solid fa-trash"></i>';remove.onclick=()=>{cart=cart.filter(item=>item.id!==line.id);save()};article.append(content,remove);lines.append(article)});document.getElementById('cartPayload').value=JSON.stringify(cart.map(({id,quantity})=>({id,quantity})))}
  function escapeHtml(value){const span=document.createElement('span');span.textContent=value;return span.innerHTML}
  document.querySelectorAll('.add-cart').forEach(button=>button.addEventListener('click',()=>{const id=Number(button.dataset.productId),existing=cart.find(line=>line.id===id);if(existing)existing.quantity++;else cart.push({id,name:button.dataset.productName,price:Number(button.dataset.productPrice),image:button.dataset.productImage,quantity:1});save();const toast=document.getElementById('shopToast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800);openCart()}));
  document.getElementById('openCart').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;backdrop.onclick=closeCart;document.getElementById('continueShopping').onclick=()=>{closeCart();document.getElementById('produits').scrollIntoView()};
  const checkoutBackdrop=document.getElementById('checkoutBackdrop');document.getElementById('openCheckout').onclick=()=>{closeCart();document.getElementById('cartPayload').value=JSON.stringify(cart.map(({id,quantity})=>({id,quantity})));checkoutBackdrop.classList.add('open');document.body.style.overflow='hidden'};document.getElementById('closeCheckout').onclick=()=>{checkoutBackdrop.classList.remove('open');document.body.style.overflow=''};checkoutBackdrop.addEventListener('click',event=>{if(event.target===checkoutBackdrop){checkoutBackdrop.classList.remove('open');document.body.style.overflow=''}});
  const products=[...document.querySelectorAll('.market-product')],desktopSearch=document.getElementById('publicShopSearch'),mobileSearch=document.getElementById('mobileShopSearch');let activeCategory='';function filter(){const query=(desktopSearch.value||mobileSearch.value).trim().toLocaleLowerCase('fr');let visible=0;products.forEach(product=>{const show=product.dataset.search.includes(query)&&(!activeCategory||product.dataset.category===activeCategory);product.hidden=!show;if(show)visible++});document.getElementById('visibleProducts').textContent=visible;document.getElementById('noProducts').hidden=visible>0}desktopSearch.oninput=()=>{mobileSearch.value=desktopSearch.value;filter()};mobileSearch.oninput=()=>{desktopSearch.value=mobileSearch.value;filter()};document.querySelectorAll('[data-category-filter]').forEach(button=>button.onclick=()=>{activeCategory=button.dataset.categoryFilter;document.querySelectorAll('.category-chips [data-category-filter]').forEach(chip=>chip.classList.toggle('active',chip.dataset.categoryFilter===activeCategory));filter();closeMobileNav();document.getElementById('produits').scrollIntoView({behavior:'smooth'})});renderCart();
});
