<?php
declare(strict_types=1);
namespace App\Application\Workflow;
use PDO;use RuntimeException;use Throwable;
final class SaveBudgetAndPlanning
{
    public function __construct(private readonly PDO $database){}
    public function execute(int $orderId,array $lines,string $label,string $start,string $end,int $userId):void
    {
        if($orderId<=0||!$lines)throw new RuntimeException('Ajoutez au moins une ligne de fourniture ou de transport.');if($start===''||$end===''||$end<$start)throw new RuntimeException('Le planning de début et de fin est invalide.');
        $order=$this->database->prepare("SELECT bc.id FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id WHERE bc.id=:id AND (d.validation_generale=1 OR d.statut_devis='valide')");$order->execute(['id'=>$orderId]);if(!$order->fetchColumn())throw new RuntimeException('Sélectionnez un bon lié à un devis validé.');
        $supplies=0.0;$transport=0.0;foreach($lines as &$line){$line['category']=strtolower((string)($line['category']??''));$line['label']=trim((string)($line['label']??''));$line['quantity']=(float)($line['quantity']??0);$line['unit_price']=(float)($line['unit_price']??0);if(!in_array($line['category'],['fourniture','transport'],true)||$line['label']===''||$line['quantity']<=0||$line['unit_price']<0)throw new RuntimeException('Une ligne de déboursé est incomplète.');$line['amount']=$line['quantity']*$line['unit_price'];if($line['category']==='transport')$transport+=$line['amount'];else$supplies+=$line['amount'];}unset($line);
        try{$this->database->beginTransaction();$statement=$this->database->prepare("INSERT INTO debourses(bon_commande_id,montant_fournitures,montant_transport,statut,valide_le,created_by) VALUES(:order_id,:supplies,:transport,'valide',NOW(),:user_id) ON DUPLICATE KEY UPDATE montant_fournitures=VALUES(montant_fournitures),montant_transport=VALUES(montant_transport),statut='valide',valide_le=NOW(),created_by=VALUES(created_by)");$statement->execute(['order_id'=>$orderId,'supplies'=>$supplies,'transport'=>$transport,'user_id'=>$userId]);$budgetId=(int)$this->database->lastInsertId();if($budgetId===0){$find=$this->database->prepare('SELECT id FROM debourses WHERE bon_commande_id=:id');$find->execute(['id'=>$orderId]);$budgetId=(int)$find->fetchColumn();}$this->database->prepare('DELETE FROM debourse_lignes WHERE debourse_id=:id')->execute(['id'=>$budgetId]);$insert=$this->database->prepare('INSERT INTO debourse_lignes(debourse_id,categorie,designation,quantite,prix_unitaire,montant,position) VALUES(:budget,:category,:label,:quantity,:unit_price,:amount,:position)');foreach($lines as $position=>$line)$insert->execute(['budget'=>$budgetId,'position'=>$position,'category'=>$line['category'],'label'=>$line['label'],'quantity'=>$line['quantity'],'unit_price'=>$line['unit_price'],'amount'=>$line['amount']]);$this->database->prepare('DELETE FROM planning_affaire WHERE bon_commande_id=:id')->execute(['id'=>$orderId]);$this->database->prepare('INSERT INTO planning_affaire(bon_commande_id,libelle,date_debut,date_fin) VALUES(:id,:label,:start,:end)')->execute(['id'=>$orderId,'label'=>$label?:'Exécution de la commande','start'=>$start,'end'=>$end]);$this->database->commit();}catch(Throwable $error){if($this->database->inTransaction())$this->database->rollBack();throw $error;}
    }
}
