<?php

declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
if (!isset($_SESSION['public_shop_csrf'])) $_SESSION['public_shop_csrf'] = bin2hex(random_bytes(24));

function publicShopEscape(mixed $value): string { return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function publicShopCategory(string $designation): string {
    $groups = ['Protection' => ['CHAUSSURE','GANT','LUNETTE','BOTTE','CASQUE'], 'Électricité' => ['SENSOR','LAMPE','MODULE','VOYANT','BATTERIE','CABLE'], 'Hydraulique' => ['VALVE','FLEXIBLE','TUYAU','POMPE'], 'Mobilier' => ['CHAISE','TABLE','TABOURET']];
    foreach ($groups as $category => $terms) foreach ($terms as $term) if (stripos($designation, $term) !== false) return $category;
    return 'Équipement';
}

$pdo = app_database();
$products = $pdo->query("SELECT p.id_produit,p.designation,p.dernier_prix,p.prix_moyen,p.stock,(SELECT filename FROM produit_image pi WHERE pi.produit_id=p.id_produit ORDER BY pi.position,pi.date_upload DESC LIMIT 1) image FROM produit p ORDER BY p.designation")->fetchAll(PDO::FETCH_ASSOC);
$success = $_SESSION['public_shop_success'] ?? null; unset($_SESSION['public_shop_success']);
$error = $_SESSION['public_shop_error'] ?? null; unset($_SESSION['public_shop_error']);
$categories = [];
foreach ($products as $product) $categories[publicShopCategory((string) $product['designation'])] = true;
?>
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Boutique publique FIDEST : équipements industriels et fournitures professionnelles.">
    <title>Boutique professionnelle | FIDEST</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="branding.css.php"><link rel="stylesheet" href="css/public-shop.css">
</head>
<body>
    <div class="market-strip"><div><span><i class="fa-solid fa-shield-halved"></i> Fournisseur professionnel de confiance</span><span><i class="fa-solid fa-phone"></i> +225 27 21 36 27 27</span><span><i class="fa-regular fa-envelope"></i> info@fidest.org</span></div></div>
    <header class="market-header"><button class="mobile-menu-trigger" id="openMobileMenu" type="button" aria-label="Ouvrir le menu"><i class="fa-solid fa-bars"></i></button><a class="market-logo" href="boutique_publique.php"><img src="img/logo_fidest.png" alt="FIDEST"><span>BOUTIQUE<small>Solutions professionnelles</small></span></a><div class="market-search"><i class="fa-solid fa-magnifying-glass"></i><input id="publicShopSearch" type="search" placeholder="Que recherchez-vous aujourd’hui ?"><button type="button">Rechercher</button></div><button class="cart-trigger" id="openCart" type="button"><span class="cart-trigger__icon"><i class="fa-solid fa-cart-shopping"></i><b id="cartCount">0</b></span><span>Mon panier<small id="cartHeaderTotal">0 FCFA</small></span></button></header>
    <div class="mobile-nav-backdrop" id="mobileNavBackdrop"></div><nav class="category-nav" id="mobileNav"><div class="mobile-nav-head"><img src="img/logo_fidest.png" alt="FIDEST"><button id="closeMobileMenu" type="button" aria-label="Fermer le menu"><i class="fa-solid fa-xmark"></i></button></div><div class="mobile-nav-title">Explorer la boutique</div><a href="#produits"><i class="fa-solid fa-border-all"></i> Tous les produits</a><?php foreach (array_keys($categories) as $category): ?><button type="button" data-category-filter="<?= publicShopEscape(mb_strtolower($category)) ?>"><i class="fa-solid fa-chevron-right"></i><?= publicShopEscape($category) ?></button><?php endforeach; ?><a href="#services"><i class="fa-solid fa-award"></i> Pourquoi FIDEST ?</a><a class="mobile-contact" href="tel:+2252721362727"><i class="fa-solid fa-headset"></i> Contacter un conseiller</a></nav>

    <main>
        <section class="market-hero"><div class="market-hero__content"><div class="hero-badge"><i class="fa-solid fa-bolt"></i> L’expertise industrielle, livrée chez vous</div><h1>Le bon équipement.<br><em>Au bon endroit.</em></h1><p>Commandez vos fournitures professionnelles en quelques clics. Notre équipe confirme la disponibilité, le prix et la livraison avec vous.</p><div class="hero-actions"><a href="#produits" class="cta-primary">Découvrir les produits <i class="fa-solid fa-arrow-right"></i></a><a href="tel:+2252721362727" class="cta-secondary"><i class="fa-solid fa-headset"></i> Parler à un conseiller</a></div><div class="hero-proof"><span><strong><?= count($products) ?>+</strong> références</span><span><strong>24h</strong> prise en charge</span><span><strong>Abidjan</strong> & Côte d’Ivoire</span></div></div><div class="market-hero__visual"><div class="hero-orbit hero-orbit--one"></div><div class="hero-orbit hero-orbit--two"></div><span class="hero-main-icon"><i class="fa-solid fa-gears"></i></span><div class="floating-card floating-card--top"><i class="fa-solid fa-truck-fast"></i><span><strong>Livraison suivie</strong><small>Selon votre localisation</small></span></div><div class="floating-card floating-card--bottom"><i class="fa-solid fa-circle-check"></i><span><strong>Qualité vérifiée</strong><small>Sélection professionnelle</small></span></div></div></section>

        <section class="trust-row" id="services"><div><i class="fa-solid fa-certificate"></i><span><strong>Produits sélectionnés</strong><small>Des références professionnelles</small></span></div><div><i class="fa-solid fa-comments"></i><span><strong>Conseil personnalisé</strong><small>Une équipe à votre écoute</small></span></div><div><i class="fa-solid fa-location-dot"></i><span><strong>Livraison adaptée</strong><small>Adresse et instructions précises</small></span></div><div><i class="fa-solid fa-file-invoice"></i><span><strong>Devis transparent</strong><small>Confirmation avant traitement</small></span></div></section>

        <?php if ($success): ?><section class="shop-message shop-message--success"><i class="fa-solid fa-circle-check"></i><div><strong>Votre demande a bien été envoyée !</strong><p>Référence : <b><?= publicShopEscape($success) ?></b>. Notre équipe vous contactera rapidement.</p></div></section><?php endif; ?>
        <?php if ($error): ?><section class="shop-message shop-message--error"><i class="fa-solid fa-triangle-exclamation"></i><div><strong>Envoi impossible</strong><p><?= publicShopEscape($error) ?></p></div></section><?php endif; ?>

        <section class="products-section" id="produits"><div class="mobile-search"><i class="fa-solid fa-magnifying-glass"></i><input id="mobileShopSearch" type="search" placeholder="Rechercher un produit…"></div><div class="section-heading"><div><span>CATALOGUE FIDEST</span><h2>Nos équipements professionnels</h2><p>Ajoutez vos articles au panier et transmettez-nous votre demande.</p></div><div class="results-count"><b id="visibleProducts"><?= count($products) ?></b> produit(s)</div></div><div class="category-chips"><button class="active" type="button" data-category-filter="">Tout voir</button><?php foreach (array_keys($categories) as $category): ?><button type="button" data-category-filter="<?= publicShopEscape(mb_strtolower($category)) ?>"><?= publicShopEscape($category) ?></button><?php endforeach; ?></div>
            <div class="market-grid" id="publicShopGrid">
            <?php foreach ($products as $product): $designation=(string)$product['designation'];$category=publicShopCategory($designation);$price=(float)($product['dernier_prix']?:$product['prix_moyen']);$stock=(int)$product['stock'];$image=$product['image']?'photo/produits/'.$product['image']:''; ?>
                <article class="market-product" data-search="<?= publicShopEscape(mb_strtolower($designation.' '.$category)) ?>" data-category="<?= publicShopEscape(mb_strtolower($category)) ?>"><div class="market-product__visual"><?php if($image): ?><img src="<?= publicShopEscape($image) ?>" alt="<?= publicShopEscape($designation) ?>" loading="lazy"><?php else: ?><div class="market-product__placeholder"><i class="fa-solid fa-box-open"></i></div><?php endif; ?><span class="availability <?= $stock>0?'in-stock':'on-order' ?>"><?= $stock>0?'En stock':'Sur commande' ?></span><span class="product-category"><?= publicShopEscape($category) ?></span></div><div class="market-product__body"><div class="product-reference">RÉF. FID-<?= (int)$product['id_produit'] ?></div><h3><?= publicShopEscape($designation) ?></h3><div class="product-rating"><span><i class="fa-solid fa-star"></i> 5.0</span><small>Qualité professionnelle</small></div><div class="market-product__bottom"><div class="public-price"><?= $price>0?number_format($price,0,',',' ').' FCFA':'Sur devis' ?><small><?= $price>0?'HT':'' ?></small></div><button class="add-cart" type="button" data-product-id="<?= (int)$product['id_produit'] ?>" data-product-name="<?= publicShopEscape($designation) ?>" data-product-price="<?= $price ?>" data-product-image="<?= publicShopEscape($image) ?>"><i class="fa-solid fa-cart-plus"></i><span>Ajouter</span></button></div></div></article>
            <?php endforeach; ?>
            </div><div class="no-products" id="noProducts" hidden><i class="fa-solid fa-magnifying-glass"></i><strong>Aucun produit trouvé</strong><p>Essayez avec un autre mot-clé ou une autre catégorie.</p></div>
        </section>
    </main>

    <footer class="public-footer"><div class="footer-brand"><img src="img/logo_fidest.png" alt="FIDEST"><p>Fournitures industrielles, dépannage et travaux publics.</p></div><div><strong>Nous contacter</strong><a href="tel:+2252721362727">+225 27 21 36 27 27</a><a href="mailto:info@fidest.org">info@fidest.org</a></div><div><strong>Nous trouver</strong><span>Abidjan, Koumassi</span><span>Zone industrielle</span></div><small>© <?= date('Y') ?> FIDEST. Tous droits réservés.</small></footer>

    <div class="cart-backdrop" id="cartBackdrop"></div><aside class="cart-drawer" id="cartDrawer" aria-label="Panier"><div class="cart-head"><div><span>VOTRE SÉLECTION</span><h2>Mon panier <b id="drawerCartCount">0</b></h2></div><button id="closeCart" type="button" aria-label="Fermer"><i class="fa-solid fa-xmark"></i></button></div><div class="cart-lines" id="cartLines"></div><div class="cart-empty" id="cartEmpty"><i class="fa-solid fa-basket-shopping"></i><strong>Votre panier est vide</strong><p>Découvrez nos produits et ajoutez vos besoins.</p><button type="button" id="continueShopping">Voir les produits</button></div><div class="cart-summary" id="cartSummary"><div><span>Total estimatif HT</span><strong id="cartTotal">0 FCFA</strong></div><p><i class="fa-solid fa-circle-info"></i> Le prix final et la disponibilité seront confirmés par notre équipe.</p><button class="checkout-button" id="openCheckout" type="button">Continuer vers la livraison <i class="fa-solid fa-arrow-right"></i></button></div></aside>

    <div class="checkout-backdrop" id="checkoutBackdrop"><section class="checkout-modal" id="commande"><button class="checkout-close" id="closeCheckout" type="button"><i class="fa-solid fa-xmark"></i></button><div class="checkout-intro"><span>DERNIÈRE ÉTAPE</span><h2>Où devons-nous livrer ?</h2><p>Renseignez vos coordonnées. Un conseiller FIDEST vous contactera pour confirmer votre commande.</p></div><form action="request/soumettre_commande_boutique.php" method="post" id="checkoutForm"><input type="hidden" name="csrf_token" value="<?= publicShopEscape($_SESSION['public_shop_csrf']) ?>"><input type="hidden" name="cart" id="cartPayload"><input class="honeypot" name="website" tabindex="-1" autocomplete="off"><div class="checkout-grid"><label><span>Nom et prénom *</span><input name="nom_contact" required autocomplete="name" placeholder="Votre nom complet"></label><label><span>Entreprise</span><input name="entreprise" autocomplete="organization" placeholder="Nom de votre société"></label><label><span>E-mail *</span><input name="email" type="email" required autocomplete="email" placeholder="vous@entreprise.com"></label><label><span>Téléphone *</span><input name="telephone" type="tel" required autocomplete="tel" placeholder="+225 00 00 00 00 00"></label><label class="full"><span>Adresse de livraison *</span><input name="adresse_livraison" required autocomplete="street-address" placeholder="Rue, quartier, bâtiment, repère…"></label><label><span>Commune *</span><input name="commune" required placeholder="Ex. Marcory"></label><label><span>Ville *</span><input name="ville" required value="Abidjan"></label><label class="full"><span>Instructions de livraison</span><textarea name="indications" rows="3" placeholder="Horaires, personne à contacter, accès au site…"></textarea></label></div><div class="checkout-submit"><div><i class="fa-solid fa-lock"></i><span><strong>Demande sécurisée</strong><small>Aucun paiement en ligne n’est demandé.</small></span></div><button type="submit">Envoyer ma demande <i class="fa-solid fa-paper-plane"></i></button></div></form></section></div>
    <div class="toast" id="shopToast"><i class="fa-solid fa-circle-check"></i><span>Produit ajouté au panier</span></div>
    <script src="js/public-shop.js"></script>
    <?php if ($success): ?><script>localStorage.removeItem('fidest_public_cart');</script><?php endif; ?>
</body>
</html>
