<?php
declare(strict_types=1);
require_once __DIR__.'/auth_check.php';require_once __DIR__.'/bootstrap.php';
use App\Domain\Billing\BillingRepository;
$billing=new BillingRepository(app_database());$metrics=$billing->metrics();$rows=$billing->search($_GET);
function h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Facturation · FIDEST</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/modules.css"><style>
.billing-hero{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:24px;padding:30px;color:#fff;background:linear-gradient(125deg,var(--brand-primary),var(--brand-primary-soft));border-radius:24px}.billing-hero h1{margin:0;color:#fff!important}.billing-hero p{margin:8px 0 0;color:#ffffffb5}.billing-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.billing-kpi{padding:19px;background:#fff;border:1px solid var(--brand-border);border-radius:16px}.billing-kpi small{color:var(--brand-text-muted);text-transform:uppercase;font-weight:800;font-size:.67rem}.billing-kpi strong{display:block;margin-top:7px;color:var(--brand-primary);font-size:1.55rem}.billing-filters{padding:18px;background:#fff;border:1px solid var(--brand-border);border-radius:16px}.billing-table{margin-top:20px;overflow:hidden;background:#fff;border:1px solid var(--brand-border);border-radius:18px}.billing-table td,.billing-table th{padding:14px;vertical-align:middle}.billing-status{display:inline-flex;padding:6px 9px;border-radius:99px;font-size:.68rem;font-weight:900}.billing-status.overdue{color:#a62c37;background:#fbe9eb}.billing-status.upcoming{color:#8a5a00;background:#fff0bf}.billing-status.scheduled{color:#14733f;background:#dcf7e8}.billing-status.unscheduled{color:#6b6e82;background:#ececf2}.schedule-form{display:flex;gap:7px}.schedule-form input{min-width:145px}.focus-row{outline:3px solid var(--brand-accent);outline-offset:-3px}@media(max-width:900px){.billing-kpis{grid-template-columns:1fr 1fr}.billing-hero{align-items:flex-start;flex-direction:column}}@media(max-width:600px){.billing-kpis{grid-template-columns:1fr}}
</style></head><body class="module-page"><nav class="navbar navbar-expand-lg navbar-dark"><div class="container"><a class="navbar-brand" href="dashboard.php"><img src="img/logo_fidest.png" alt="FIDEST"></a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navbarNav"><?php include 'menu.php'; ?></div></div></nav>
<main class="container"><section class="billing-hero"><div><div class="text-warning fw-bold small">PILOTAGE FINANCIER</div><h1>Facturation</h1><p>Programmez les factures, surveillez les échéances et traitez les alertes.</p></div><div class="d-flex gap-2 flex-wrap"><a target="_blank" href="request/export_billing_pdf.php?<?=h(http_build_query($_GET))?>" class="btn btn-light"><i class="fa-solid fa-file-pdf text-danger"></i> Export PDF</a><a href="request/export_billing_excel.php?<?=h(http_build_query($_GET))?>" class="btn btn-light"><i class="fa-solid fa-file-excel text-success"></i> Export Excel</a><a href="generer_devis.php" class="btn btn-warning"><i class="fa-solid fa-plus"></i> Nouveau devis</a></div></section>
<?php if(isset($_GET['updated'])):?><div class="alert alert-success">La date de facturation a été mise à jour.</div><?php endif;?>
<section class="billing-kpis"><div class="billing-kpi"><small>Montant programmé</small><strong><?=number_format((float)$metrics['scheduled_amount'],0,',',' ')?> <small>FCFA</small></strong></div><div class="billing-kpi"><small>Dans les 7 jours</small><strong><?=(int)$metrics['upcoming']?></strong></div><div class="billing-kpi"><small>En retard</small><strong><?=(int)$metrics['overdue']?></strong></div><div class="billing-kpi"><small>À programmer</small><strong><?=(int)$metrics['unscheduled']?></strong></div></section>
<form class="billing-filters row g-2" method="get"><div class="col-md-7"><input class="form-control" name="q" value="<?=h($_GET['q']??'')?>" placeholder="N° devis, client ou destinataire"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Tous les statuts</option><?php foreach(['upcoming'=>'Dans les 7 jours','overdue'=>'En retard','scheduled'=>'Programmées','unscheduled'=>'À programmer'] as $v=>$l):?><option value="<?=$v?>" <?=($_GET['status']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="fa-solid fa-filter"></i> Filtrer</button></div></form>
<section class="billing-table table-responsive"><table class="table mb-0"><thead><tr><th>Devis</th><th>Client</th><th>Montant TTC</th><th>État</th><th>Date de facturation</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $row):$date=$row['date_facturation_prevue'];$days=$date?(int)((strtotime($date)-strtotime(date('Y-m-d')))/86400):null;$status=$date===null?'unscheduled':($days<0?'overdue':($days<=7?'upcoming':'scheduled'));$labels=['unscheduled'=>'À programmer','overdue'=>'En retard','upcoming'=>'Imminente','scheduled'=>'Programmée'];?><tr id="devis-<?=$row['id']?>" class="<?=((int)($_GET['focus']??0)===(int)$row['id'])?'focus-row':''?>"><td><strong><?=h($row['numero_devis'])?></strong><br><small class="text-muted">Émis le <?=h($row['date_emission'])?></small></td><td><?=h($row['nom_client']?:strtok((string)$row['destine_a'],"\n"))?></td><td><strong><?=number_format((float)$row['total_ttc'],0,',',' ')?> FCFA</strong></td><td><span class="billing-status <?=$status?>"><?=$labels[$status]?></span></td><td><form class="schedule-form" method="post" action="request/schedule_billing.php"><input type="hidden" name="devis_id" value="<?=$row['id']?>"><input type="date" class="form-control form-control-sm" name="date_facturation" value="<?=h($date)?>"><button class="btn btn-sm btn-outline-primary" title="Enregistrer"><i class="fa-solid fa-check"></i></button></form></td><td><a class="btn btn-sm btn-light" target="_blank" href="request/preview_pdf.php?devisId=<?=$row['id']?>"><i class="fa-regular fa-eye"></i></a> <a class="btn btn-sm btn-light" href="modifier_devis.php?devisId=<?=$row['id']?>"><i class="fa-solid fa-pen"></i></a></td></tr><?php endforeach;?></tbody></table><?php if(!$rows):?><div class="p-5 text-center text-muted">Aucun devis ne correspond à ces critères.</div><?php endif;?></section></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script></body></html>
