<?php
declare(strict_types=1);
require_once __DIR__.'/auth_check.php';require_once __DIR__.'/bootstrap.php';
use App\Domain\Offer\OfferRepository;
$repository=new OfferRepository(app_database());$clients=(new App\Domain\Client\ClientRepository(app_database()))->all();
$statuses=['en_cours'=>'En cours','remporte'=>'Remporté','termine'=>'Terminé','non_remporte'=>'Non remporté'];
$id=(int)($_GET['id']??$_POST['id']??0);$offer=$repository->find($id);if(!$offer){http_response_code(404);exit('Appel d’offre introuvable.');}
if($_SERVER['REQUEST_METHOD']==='POST'){$status=(string)($_POST['statut']??'en_cours');if(!isset($statuses[$status]))$status='en_cours';$repository->update($id,['number'=>trim((string)$_POST['num_offre']),'offer_date'=>(string)$_POST['date_offre'],'reference'=>trim((string)$_POST['reference_offre']),'title'=>trim((string)$_POST['titre_offre']),'estimated_amount'=>$_POST['montant_estime']!==''?(float)$_POST['montant_estime']:null,'sales_contact'=>trim((string)$_POST['commercial_dedie']),'created_at'=>(string)$_POST['date_creat_offre'],'client_id'=>(int)$_POST['client_id'],'response_deadline'=>(string)$_POST['date_limite_reponse'],'status'=>$status,'loss_reason'=>$status==='non_remporte'?trim((string)$_POST['motif_perte']):null]);header('Location: liste_offre.php');exit;}
function e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modifier l’appel d’offre</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/modules.css"></head><body class="module-page"><?php include __DIR__.'/partials/navbar.php';?><main class="container"><div class="module-heading"><div class="module-heading__copy"><div><h1>Modifier l’appel d’offre</h1><p>Actualisez le client, l’échéance et le résultat commercial.</p></div></div><a href="liste_offre.php" class="btn btn-outline-secondary">Retour</a></div><form method="post" class="card p-4"><input type="hidden" name="id" value="<?=$id?>"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Client *</label><select class="form-select" name="client_id" required><option value="">Choisir</option><?php foreach($clients as $client):?><option value="<?=(int)$client['id_client']?>" <?=(int)$offer['client_id']===(int)$client['id_client']?'selected':''?>><?=e($client['nom_client'])?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label">Numéro *</label><input class="form-control" name="num_offre" value="<?=e($offer['num_offre'])?>" required></div><div class="col-md-6"><label class="form-label">Référence *</label><input class="form-control" name="reference_offre" value="<?=e($offer['reference_offre'])?>" required></div><div class="col-md-8"><label class="form-label">Titre de l’appel d’offre *</label><input class="form-control" name="titre_offre" value="<?=e($offer['titre_offre']?:$offer['reference_offre'])?>" required></div><div class="col-md-4"><label class="form-label">Montant estimé (FCFA)</label><input type="number" min="0" step="0.01" class="form-control" name="montant_estime" value="<?=e($offer['montant_estime'])?>"></div>
<div class="col-md-3"><label class="form-label">Reçu le *</label><input type="date" class="form-control" name="date_offre" value="<?=e($offer['date_offre'])?>" required></div><div class="col-md-3"><label class="form-label">Réponse avant *</label><input type="date" class="form-control" name="date_limite_reponse" value="<?=e($offer['date_limite_reponse'])?>" required></div>
<div class="col-md-6"><label class="form-label">Commercial dédié *</label><input class="form-control" name="commercial_dedie" value="<?=e($offer['commercial_dedie'])?>" required></div><div class="col-md-6"><label class="form-label">Date de création *</label><input type="date" class="form-control" name="date_creat_offre" value="<?=e($offer['date_creat_offre'])?>" required></div>
<div class="col-md-6"><label class="form-label">Statut *</label><select class="form-select" id="status" name="statut"><?php foreach($statuses as $value=>$label):?><option value="<?=$value?>" <?=$offer['statut']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="col-md-6" id="loss"><label class="form-label">Motif de non-attribution</label><input class="form-control" id="reason" name="motif_perte" value="<?=e($offer['motif_perte'])?>"></div>
<div class="col-12"><?php if($offer['fichier_ao']):?><a target="_blank" class="btn btn-outline-secondary me-2" href="<?=e($offer['fichier_ao'])?>">Voir le document source</a><?php else:?><span class="text-danger me-3">Document source absent (ancienne donnée)</span><?php endif;?><button class="btn btn-primary">Enregistrer</button></div></div></form></main><script>const s=document.getElementById('status'),z=document.getElementById('loss'),r=document.getElementById('reason');function sync(){z.hidden=s.value!=='non_remporte';r.required=s.value==='non_remporte'}s.addEventListener('change',sync);sync();</script></body></html>
