<?php
declare(strict_types=1);
require_once __DIR__.'/auth_check.php'; require_once __DIR__.'/bootstrap.php';
$pdo=app_database();
function wf_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function wf_money(mixed $v):string{return number_format((float)$v,0,',',' ').' FCFA';}
$_SESSION['workflow_csrf'] ??= bin2hex(random_bytes(24)); $error='';

if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!hash_equals((string)$_SESSION['workflow_csrf'],(string)($_POST['csrf']??''))) throw new RuntimeException('Session expirée.');
  $action=(string)($_POST['action']??''); $bcId=(int)($_POST['bc_id']??0);
  $pdo->beginTransaction();
  $order=$pdo->prepare('SELECT bc.*,d.validation_generale,d.statut_devis FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id WHERE bc.id=:id');$order->execute(['id'=>$bcId]);$order=$order->fetch();
  if(!$order || ((int)$order['validation_generale']!==1 && $order['statut_devis']!=='valide')) throw new RuntimeException('Un devis validé et son bon de commande sont requis.');
  if($action==='validate_budget'){
   $sup=(float)($_POST['fournitures']??0);$transport=(float)($_POST['transport']??0);$start=(string)($_POST['date_debut']??'');$end=(string)($_POST['date_fin']??'');
   if($sup<0||$transport<0||$start===''||$end===''||$end<$start)throw new RuntimeException('Renseignez un déboursé et un planning cohérents.');
   $s=$pdo->prepare("INSERT INTO debourses(bon_commande_id,montant_fournitures,montant_transport,statut,valide_le,created_by) VALUES(:bc,:f,:t,'valide',NOW(),:u) ON DUPLICATE KEY UPDATE montant_fournitures=VALUES(montant_fournitures),montant_transport=VALUES(montant_transport),statut='valide',valide_le=NOW()");$s->execute(['bc'=>$bcId,'f'=>$sup,'t'=>$transport,'u'=>(int)($_SESSION['user_id']??0)]);
   $pdo->prepare('DELETE FROM planning_affaire WHERE bon_commande_id=:bc')->execute(['bc'=>$bcId]);
   $pdo->prepare('INSERT INTO planning_affaire(bon_commande_id,libelle,date_debut,date_fin) VALUES(:bc,:label,:start,:end)')->execute(['bc'=>$bcId,'label'=>trim((string)($_POST['libelle']??''))?:'Exécution','start'=>$start,'end'=>$end]);
  }elseif($action==='analyze_feb'){
   $status=(string)($_POST['decision']??'');if(!in_array($status,['approuve','rejete'],true))throw new RuntimeException('Décision FEB invalide.');
   $pdo->prepare('UPDATE fiches_expression_besoin SET statut=:s,motif_rejet=:m WHERE bon_commande_id=:bc AND date_disponibilite<=CURRENT_DATE')->execute(['s'=>$status,'m'=>$status==='rejete'?trim((string)($_POST['motif']??'')):null,'bc'=>$bcId]);
  }elseif($action==='disburse'){
   $feb=$pdo->prepare("SELECT id FROM fiches_expression_besoin WHERE bon_commande_id=:bc AND statut='approuve'");$feb->execute(['bc'=>$bcId]);$febId=(int)$feb->fetchColumn();if(!$febId)throw new RuntimeException('La FEB doit être approuvée.');
   $amount=(float)($_POST['montant']??0);if($amount<=0)throw new RuntimeException('Le montant du décaissement est obligatoire.');
   $pdo->prepare('INSERT INTO decaissements(feb_id,montant,date_decaissement,reference_paiement) VALUES(:feb,:amount,:date,:ref)')->execute(['feb'=>$febId,'amount'=>$amount,'date'=>(string)$_POST['date'],'ref'=>trim((string)($_POST['reference']??''))?:null]);
  }elseif($action==='invoice'){
   $registry=json_decode((string)@file_get_contents(__DIR__.'/data/bl_registry.json'),true);$signed=false;foreach(($registry['items']??[]) as $item){if((int)($item['devisId']??0)===(int)$order['devis_id']){$signed=true;break;}}
   if(!$signed)throw new RuntimeException('Le BL signé doit être intégré avant la facturation.');
   $amount=(float)($_POST['montant']??0);if($amount<=0)throw new RuntimeException('Montant de facture invalide.');
   $pdo->prepare("INSERT INTO factures_clients(bon_commande_id,numero_facture,date_facture,date_echeance,montant_ttc) VALUES(:bc,:num,:date,:due,:amount)")->execute(['bc'=>$bcId,'num'=>trim((string)$_POST['numero']),'date'=>(string)$_POST['date'],'due'=>(string)$_POST['echeance'],'amount'=>$amount]);
  }elseif($action==='payment'){
   $invoice=$pdo->prepare('SELECT id,montant_ttc FROM factures_clients WHERE bon_commande_id=:bc');$invoice->execute(['bc'=>$bcId]);$invoice=$invoice->fetch();if(!$invoice)throw new RuntimeException('La facture doit être émise.');
   $amount=(float)($_POST['montant']??0);if($amount<=0)throw new RuntimeException('Montant encaissé invalide.');
   $pdo->prepare('INSERT INTO encaissements(facture_id,montant,date_encaissement,reference_paiement) VALUES(:id,:amount,:date,:ref)')->execute(['id'=>$invoice['id'],'amount'=>$amount,'date'=>(string)$_POST['date'],'ref'=>trim((string)($_POST['reference']??''))?:null]);
   $paid=$pdo->prepare('SELECT COALESCE(SUM(montant),0) FROM encaissements WHERE facture_id=:id');$paid->execute(['id'=>$invoice['id']]);$pdo->prepare('UPDATE factures_clients SET statut=:s WHERE id=:id')->execute(['s'=>(float)$paid->fetchColumn()>=(float)$invoice['montant_ttc']?'payee':'partiellement_payee','id'=>$invoice['id']]);
  }else throw new RuntimeException('Action inconnue.');
  $pdo->commit();header('Location: suivi_affaires.php?updated=1');exit;
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}

// Une FEB devient visible exactement sept jours avant le premier démarrage planifié.
$pdo->exec("INSERT IGNORE INTO fiches_expression_besoin(bon_commande_id,numero_feb,date_disponibilite,montant_demande)
 SELECT d.bon_commande_id,CONCAT('FEB-',YEAR(MIN(p.date_debut)),'-',LPAD(d.bon_commande_id,5,'0')),DATE_SUB(MIN(p.date_debut),INTERVAL 7 DAY),d.montant_fournitures+d.montant_transport FROM debourses d JOIN planning_affaire p ON p.bon_commande_id=d.bon_commande_id WHERE d.statut='valide' GROUP BY d.bon_commande_id,d.montant_fournitures,d.montant_transport");
$rows=$pdo->query("SELECT bc.id bc_id,bc.numero_bc,bc.reference_client,bc.devis_id,d.numero_devis,d.total_ttc,c.nom_client,o.num_offre,
 db.montant_fournitures,db.montant_transport,db.statut debourse_statut,MIN(p.date_debut) date_debut,MAX(p.date_fin) date_fin,
 feb.id feb_id,feb.numero_feb,feb.date_disponibilite,feb.statut feb_statut,f.id facture_id,f.numero_facture,f.montant_ttc facture_montant,f.statut facture_statut,
 COALESCE((SELECT SUM(x.montant) FROM decaissements x WHERE x.feb_id=feb.id),0) sorties,
 COALESCE((SELECT SUM(e.montant) FROM encaissements e WHERE e.facture_id=f.id),0) entrees
 FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id JOIN offre o ON o.id_offre=d.offre_id LEFT JOIN client c ON c.id_client=d.client_id LEFT JOIN debourses db ON db.bon_commande_id=bc.id LEFT JOIN planning_affaire p ON p.bon_commande_id=bc.id LEFT JOIN fiches_expression_besoin feb ON feb.bon_commande_id=bc.id LEFT JOIN factures_clients f ON f.bon_commande_id=bc.id WHERE d.archived_at IS NULL AND (d.validation_generale=1 OR d.statut_devis='valide') GROUP BY bc.id ORDER BY bc.id DESC")->fetchAll();
$registry=json_decode((string)@file_get_contents(__DIR__.'/data/bl_registry.json'),true);$signed=[];foreach(($registry['items']??[]) as $i)$signed[(int)($i['devisId']??0)]=true;
$totals=$pdo->query('SELECT (SELECT COALESCE(SUM(montant),0) FROM encaissements) entrees,(SELECT COALESCE(SUM(montant),0) FROM decaissements) sorties')->fetch();
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Suivi des affaires · FIDEST</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/modules.css"><style>
.workflow-hero{padding:28px;border-radius:22px;background:linear-gradient(125deg,var(--brand-primary),var(--brand-primary-soft));color:#fff}.workflow-hero h1{color:#fff!important}.money-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:20px 0}.money-card,.case{background:#fff;border:1px solid var(--brand-border);border-radius:17px;padding:18px}.money-card strong{display:block;font-size:1.5rem;color:var(--brand-primary)}.case{margin-bottom:16px}.steps{display:grid;grid-template-columns:repeat(9,1fr);gap:5px;margin:14px 0}.step{height:8px;background:#e2e3ea;border-radius:9px}.step.done{background:#15935b}.step.current{background:var(--brand-accent)}.case-head{display:flex;justify-content:space-between;gap:12px}.actions{padding-top:14px;border-top:1px solid var(--brand-border)}@media(max-width:800px){.money-grid{grid-template-columns:1fr}.steps{grid-template-columns:repeat(3,1fr)}}
</style></head><body class="module-page"><?php include __DIR__.'/partials/navbar.php';?><main class="container"><section class="workflow-hero"><div class="small text-warning fw-bold">PARCOURS OPÉRATIONNEL · 9 ÉTAPES</div><h1>Suivi des affaires</h1><p class="mb-0">Chaque action est disponible uniquement lorsque l’étape précédente est terminée.</p></section>
<?php if($error):?><div class="alert alert-danger mt-3"><?=wf_h($error)?></div><?php elseif(isset($_GET['updated'])):?><div class="alert alert-success mt-3">Le suivi a été mis à jour.</div><?php endif;?>
<section class="money-grid"><div class="money-card"><small>Entrées réellement encaissées</small><strong><?=wf_money($totals['entrees'])?></strong></div><div class="money-card"><small>Sorties réellement décaissées</small><strong><?=wf_money($totals['sorties'])?></strong></div><div class="money-card"><small>Solde réel (entrées − sorties)</small><strong><?=wf_money((float)$totals['entrees']-(float)$totals['sorties'])?></strong></div></section>
<?php if(!$rows):?><div class="alert alert-info">Aucune affaire n’a encore atteint le bon de commande après validation du devis.</div><?php endif;?>
<?php foreach($rows as $r):$hasBudget=$r['debourse_statut']==='valide';$febVisible=$r['feb_id']&&$r['date_disponibilite']<=date('Y-m-d');$hasDisbursement=(float)$r['sorties']>0;$hasBl=!empty($signed[(int)$r['devis_id']]);$hasInvoice=!empty($r['facture_id']);$hasPayment=(float)$r['entrees']>0;$completed=3+($hasBudget?1:0)+($febVisible?1:0)+($hasDisbursement?1:0)+($hasBl?1:0)+($hasInvoice?1:0)+($hasPayment?1:0);?>
<article class="case"><div class="case-head"><div><h2 class="h5 mb-1"><?=wf_h($r['num_offre'])?> · <?=wf_h($r['nom_client'])?></h2><small><?=wf_h($r['numero_devis'])?> → <?=wf_h($r['numero_bc'])?></small></div><span class="badge text-bg-primary align-self-start">Étape <?=min($completed,9)?> / 9</span></div><div class="steps" title="Progression"><?php for($i=1;$i<=9;$i++):?><span class="step <?=$i<$completed?'done':($i===$completed?'current':'')?>"></span><?php endfor;?></div>
<div class="row g-3 small mb-3"><div class="col-md-3"><strong>Déboursé</strong><br><?= $hasBudget?wf_money((float)$r['montant_fournitures']+(float)$r['montant_transport']):'À renseigner'?></div><div class="col-md-3"><strong>Planning</strong><br><?=wf_h($r['date_debut']?:'—')?> → <?=wf_h($r['date_fin']?:'—')?></div><div class="col-md-3"><strong>FEB</strong><br><?=wf_h($febVisible?($r['numero_feb'].' · '.$r['feb_statut']):($r['date_disponibilite']?'Visible le '.$r['date_disponibilite']:'En attente'))?></div><div class="col-md-3"><strong>Réel</strong><br>Entrées <?=wf_money($r['entrees'])?> · Sorties <?=wf_money($r['sorties'])?></div></div>
<div class="actions">
<?php if(!$hasBudget):?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=wf_h($_SESSION['workflow_csrf'])?>"><input type="hidden" name="action" value="validate_budget"><input type="hidden" name="bc_id" value="<?=$r['bc_id']?>"><div class="col-md-2"><input required min="0" type="number" class="form-control" name="fournitures" placeholder="Fournitures"></div><div class="col-md-2"><input required min="0" type="number" class="form-control" name="transport" placeholder="Transport"></div><div class="col-md-2"><input class="form-control" name="libelle" placeholder="Phase planning"></div><div class="col-md-2"><input required type="date" class="form-control" name="date_debut"></div><div class="col-md-2"><input required type="date" class="form-control" name="date_fin"></div><div class="col-md-2"><button class="btn btn-primary w-100">Valider déboursé</button></div></form>
<?php elseif($febVisible&&$r['feb_statut']==='a_analyser'):?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=wf_h($_SESSION['workflow_csrf'])?>"><input type="hidden" name="action" value="analyze_feb"><input type="hidden" name="bc_id" value="<?=$r['bc_id']?>"><div class="col-md-3"><select name="decision" class="form-select"><option value="approuve">Approuver la FEB</option><option value="rejete">Rejeter la FEB</option></select></div><div class="col-md-6"><input class="form-control" name="motif" placeholder="Motif si rejet"></div><div class="col-md-3"><button class="btn btn-primary w-100">Enregistrer l’analyse</button></div></form>
<?php elseif($febVisible&&$r['feb_statut']==='approuve'&&!$hasDisbursement):?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=wf_h($_SESSION['workflow_csrf'])?>"><input type="hidden" name="action" value="disburse"><input type="hidden" name="bc_id" value="<?=$r['bc_id']?>"><div class="col-md-3"><input required type="number" min="1" name="montant" class="form-control" placeholder="Montant décaissé"></div><div class="col-md-3"><input required type="date" name="date" value="<?=date('Y-m-d')?>" class="form-control"></div><div class="col-md-3"><input name="reference" class="form-control" placeholder="Référence paiement"></div><div class="col-md-3"><button class="btn btn-primary w-100">Décaisser</button></div></form>
<?php elseif($hasDisbursement&&!$hasBl):?><a class="btn btn-outline-primary" href="request/upload_bl.php?devisId=<?=$r['devis_id']?>">Étape suivante : intégrer le BL signé</a>
<?php elseif($hasBl&&!$hasInvoice):?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=wf_h($_SESSION['workflow_csrf'])?>"><input type="hidden" name="action" value="invoice"><input type="hidden" name="bc_id" value="<?=$r['bc_id']?>"><div class="col-md-3"><input required name="numero" class="form-control" placeholder="N° facture"></div><div class="col-md-2"><input required type="date" name="date" value="<?=date('Y-m-d')?>" class="form-control"></div><div class="col-md-2"><input required type="date" name="echeance" class="form-control"></div><div class="col-md-3"><input required type="number" min="1" name="montant" value="<?=(float)$r['total_ttc']?>" class="form-control"></div><div class="col-md-2"><button class="btn btn-primary w-100">Émettre facture</button></div></form>
<?php elseif($hasInvoice&&$r['facture_statut']!=='payee'):?><form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=wf_h($_SESSION['workflow_csrf'])?>"><input type="hidden" name="action" value="payment"><input type="hidden" name="bc_id" value="<?=$r['bc_id']?>"><div class="col-md-3"><input required type="number" min="1" name="montant" class="form-control" placeholder="Montant encaissé"></div><div class="col-md-3"><input required type="date" name="date" value="<?=date('Y-m-d')?>" class="form-control"></div><div class="col-md-3"><input name="reference" class="form-control" placeholder="Référence paiement"></div><div class="col-md-3"><button class="btn btn-success w-100">Enregistrer encaissement</button></div></form>
<?php else:?><span class="text-success fw-bold"><i class="fa-solid fa-circle-check"></i> Affaire soldée</span><?php endif;?></div></article><?php endforeach;?></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script></body></html>
