<?php
declare(strict_types=1);
namespace App\Domain\Analytics;
use DateTimeImmutable;use PDO;

final class AnalyticsRepository
{
    public function __construct(private readonly PDO $db){}
    public function summary(array $signedItems,string $start,string $end):array
    {
        $aoStatement=$this->db->prepare("SELECT COUNT(*) participated_count,COALESCE(SUM(COALESCE(d.total_ttc,o.montant_estime,0)),0) participated_amount,SUM(o.statut='remporte') won_count,COALESCE(SUM(CASE WHEN o.statut='remporte' THEN COALESCE(d.total_ttc,o.montant_estime,0) ELSE 0 END),0) won_amount FROM offre o LEFT JOIN quote_offer_reservations r ON r.offer_id=o.id_offre LEFT JOIN devis d ON d.id=r.quote_id WHERE o.archived_at IS NULL AND o.date_offre BETWEEN :start AND :end");$aoStatement->execute(['start'=>$start,'end'=>$end]);$ao=$aoStatement->fetch()?:[];
        $orderStatement=$this->db->prepare("SELECT COUNT(*) order_count,COALESCE(SUM(COALESCE(bc.montant,d.total_ttc,0)),0) order_amount,SUM(bc.statut='annule') cancelled_count FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND bc.date_commande BETWEEN :start AND :end");$orderStatement->execute(['start'=>$start,'end'=>$end]);$orders=$orderStatement->fetch()?:[];
        $cashStatement=$this->db->prepare("SELECT (SELECT COALESCE(SUM(e.montant),0) FROM encaissements e JOIN factures_clients f ON f.id=e.facture_id JOIN bons_commande bc ON bc.id=f.bon_commande_id JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND e.date_encaissement BETWEEN :in_start AND :in_end) cash_in,(SELECT COALESCE(SUM(x.montant),0) FROM decaissements x JOIN fiches_expression_besoin feb ON feb.id=x.feb_id JOIN bons_commande bc ON bc.id=feb.bon_commande_id JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND x.date_decaissement BETWEEN :out_start AND :out_end) cash_out");$cashStatement->execute(['in_start'=>$start,'in_end'=>$end,'out_start'=>$start,'out_end'=>$end]);$cash=$cashStatement->fetch()?:[];
        $deliveryRows=$this->db->query("SELECT bc.id,bc.devis_id,bc.statut,COALESCE(bc.montant,d.total_ttc,0) amount,COALESCE(MAX(p.date_fin),CASE WHEN d.delai_livraison_jours>0 THEN DATE_ADD(bc.date_commande,INTERVAL d.delai_livraison_jours DAY) END) expected_date FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id LEFT JOIN planning_affaire p ON p.bon_commande_id=bc.id WHERE d.archived_at IS NULL GROUP BY bc.id")->fetchAll();
        $signed=[];foreach($signedItems as $item)$signed[(int)($item['devisId']??0)]=(string)($item['signedAt']??'');
        $delivery=['delivered_count'=>0,'delivered_amount'=>0.0,'on_time_count'=>0,'late_count'=>0,'unfulfilled_count'=>0,'unfulfilled_amount'=>0.0];$today=new DateTimeImmutable('today');
        foreach($deliveryRows as $row){$quoteId=(int)$row['devis_id'];$expected=$row['expected_date']?new DateTimeImmutable((string)$row['expected_date']):null;if(isset($signed[$quoteId])){$actual=new DateTimeImmutable($signed[$quoteId]);if($actual->format('Y-m-d')<$start||$actual->format('Y-m-d')>$end)continue;$delivery['delivered_count']++;$delivery['delivered_amount']+=(float)$row['amount'];if($expected){if($actual->format('Y-m-d')<=$expected->format('Y-m-d'))$delivery['on_time_count']++;else $delivery['late_count']++;}}elseif($expected&&$expected->format('Y-m-d')>=$start&&$expected->format('Y-m-d')<=$end&&$row['statut']!=='annule'&&$expected<$today){$delivery['unfulfilled_count']++;$delivery['unfulfilled_amount']+=(float)$row['amount'];}}
        $completed=$delivery['on_time_count']+$delivery['late_count'];$delivery['on_time_rate']=$completed?round(100*$delivery['on_time_count']/$completed,1):0;$delivery['late_rate']=$completed?round(100*$delivery['late_count']/$completed,1):0;
        return $ao+$orders+$cash+$delivery+['profit'=>(float)($cash['cash_in']??0)-(float)($cash['cash_out']??0)];
    }
    public function monthly(array $signedItems,string $rangeStart,string $rangeEnd):array
    {
        $start=(new DateTimeImmutable($rangeStart))->modify('first day of this month');$finish=(new DateTimeImmutable($rangeEnd))->modify('first day of this month');$monthCount=min(60,((int)$start->diff($finish)->format('%y')*12+(int)$start->diff($finish)->format('%m'))+1);$labels=[];$data=[];for($i=0;$i<$monthCount;$i++){$date=$start->modify("+$i months");$key=$date->format('Y-m');$labels[$key]=$date->format('m/Y');$data[$key]=['ao_count'=>0,'ao_amount'=>0.0,'won_count'=>0,'won_amount'=>0.0,'orders_count'=>0,'orders_amount'=>0.0,'delivered_count'=>0,'delivered_amount'=>0.0,'cash_in'=>0.0,'cash_out'=>0.0];}
        $ao=$this->db->prepare("SELECT DATE_FORMAT(o.date_offre,'%Y-%m') month,COUNT(*) count,COALESCE(SUM(COALESCE(d.total_ttc,o.montant_estime,0)),0) amount,SUM(o.statut='remporte') won_count,COALESCE(SUM(CASE WHEN o.statut='remporte' THEN COALESCE(d.total_ttc,o.montant_estime,0) ELSE 0 END),0) won_amount FROM offre o LEFT JOIN quote_offer_reservations r ON r.offer_id=o.id_offre LEFT JOIN devis d ON d.id=r.quote_id WHERE o.archived_at IS NULL AND o.date_offre BETWEEN :start AND :end GROUP BY month");$ao->execute(['start'=>$rangeStart,'end'=>$rangeEnd]);foreach($ao->fetchAll() as $r)if(isset($data[$r['month']])){$data[$r['month']]['ao_count']=(int)$r['count'];$data[$r['month']]['ao_amount']=(float)$r['amount'];$data[$r['month']]['won_count']=(int)$r['won_count'];$data[$r['month']]['won_amount']=(float)$r['won_amount'];}
        $orders=$this->db->prepare("SELECT DATE_FORMAT(bc.date_commande,'%Y-%m') month,COUNT(*) count,COALESCE(SUM(COALESCE(bc.montant,d.total_ttc,0)),0) amount FROM bons_commande bc JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND bc.date_commande BETWEEN :start AND :end GROUP BY month");$orders->execute(['start'=>$rangeStart,'end'=>$rangeEnd]);foreach($orders->fetchAll() as $r)if(isset($data[$r['month']])){$data[$r['month']]['orders_count']=(int)$r['count'];$data[$r['month']]['orders_amount']=(float)$r['amount'];}
        $incoming=$this->db->prepare("SELECT DATE_FORMAT(e.date_encaissement,'%Y-%m') month,SUM(e.montant) amount FROM encaissements e JOIN factures_clients f ON f.id=e.facture_id JOIN bons_commande bc ON bc.id=f.bon_commande_id JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND e.date_encaissement BETWEEN :start AND :end GROUP BY month");$incoming->execute(['start'=>$rangeStart,'end'=>$rangeEnd]);foreach($incoming->fetchAll() as $r)if(isset($data[$r['month']]))$data[$r['month']]['cash_in']=(float)$r['amount'];
        $outgoing=$this->db->prepare("SELECT DATE_FORMAT(x.date_decaissement,'%Y-%m') month,SUM(x.montant) amount FROM decaissements x JOIN fiches_expression_besoin feb ON feb.id=x.feb_id JOIN bons_commande bc ON bc.id=feb.bon_commande_id JOIN devis d ON d.id=bc.devis_id WHERE d.archived_at IS NULL AND x.date_decaissement BETWEEN :start AND :end GROUP BY month");$outgoing->execute(['start'=>$rangeStart,'end'=>$rangeEnd]);foreach($outgoing->fetchAll() as $r)if(isset($data[$r['month']]))$data[$r['month']]['cash_out']=(float)$r['amount'];
        $amounts=$this->db->query('SELECT id,total_ttc FROM devis WHERE archived_at IS NULL')->fetchAll(PDO::FETCH_KEY_PAIR);foreach($signedItems as $item){try{$date=new DateTimeImmutable((string)($item['signedAt']??''));}catch(\Throwable){continue;}if($date->format('Y-m-d')<$rangeStart||$date->format('Y-m-d')>$rangeEnd)continue;$id=(int)($item['devisId']??0);$key=$date->format('Y-m');if(isset($data[$key],$amounts[$id])){$data[$key]['delivered_count']++;$data[$key]['delivered_amount']+=(float)$amounts[$id];}}
        $result=['labels'=>array_values($labels)];foreach(['ao_count','ao_amount','won_count','won_amount','orders_count','orders_amount','delivered_count','delivered_amount','cash_in','cash_out'] as $field)$result[$field]=array_column(array_values($data),$field);return $result;
    }
}
