ALTER TABLE user_devis
    ADD COLUMN IF NOT EXISTS telephone VARCHAR(40) NULL,
    ADD COLUMN IF NOT EXISTS fonction VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS departement VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS bio TEXT NULL,
    ADD COLUMN IF NOT EXISTS adresse VARCHAR(255) NULL;
