ALTER TABLE client ADD COLUMN IF NOT EXISTS logo_client VARCHAR(255) DEFAULT NULL AFTER date_creat_client;
ALTER TABLE archive_client ADD COLUMN IF NOT EXISTS logo_client VARCHAR(255) DEFAULT NULL AFTER date_creat_client;
ALTER TABLE offre ADD COLUMN IF NOT EXISTS titre_offre VARCHAR(255) DEFAULT NULL AFTER reference_offre;
ALTER TABLE offre ADD COLUMN IF NOT EXISTS montant_estime DECIMAL(15,2) DEFAULT NULL AFTER titre_offre;
ALTER TABLE archive_offre ADD COLUMN IF NOT EXISTS titre_offre VARCHAR(255) DEFAULT NULL AFTER reference_offre;
ALTER TABLE archive_offre ADD COLUMN IF NOT EXISTS montant_estime DECIMAL(15,2) DEFAULT NULL AFTER titre_offre;
