<?php
declare(strict_types=1);
namespace App\Application\Treasury;
use PDO;use RuntimeException;
final class ManageTreasuryLedger{
public function __construct(private readonly PDO $db){}
public function execute(int $user,string $action,array $data):void{
$amount=(float)($data['amount']??0);$date=(string)($data['date']??date('Y-m-d'));if(!in_array($action,['transfer','return','entry','out','confirm_invoice','postpone_invoice','cancel_invoice'],true))throw new RuntimeException('Opération de trésorerie inconnue.');
if(in_array($action,['transfer','return','entry','out'],true)){if($amount<=0||!self::date($date))throw new RuntimeException('Montant ou date invalide.');$b=$this->balances();if($action==='transfer'&&$amount>$b['entries'])throw new RuntimeException('Le solde des entrées réelles est insuffisant.');if(in_array($action,['return','out'],true)&&$amount>$b['available'])throw new RuntimeException('Le disponible réel du jour est insuffisant.');[$type,$direction]=['transfer'=>['transfer_to_available','out'],'return'=>['return_to_entries','in'],'entry'=>['manual_entry','in'],'out'=>['manual_out','out']][$action];$s=$this->db->prepare('INSERT INTO treasury_ledger(movement_type,direction,amount,movement_date,reference,note,created_by)VALUES(:type,:direction,:amount,:date,:reference,:note,:user)');$s->execute(['type'=>$type,'direction'=>$direction,'amount'=>$amount,'date'=>$date,'reference'=>trim((string)($data['reference']??''))?:null,'note'=>trim((string)($data['note']??''))?:null,'user'=>$user]);return;}
$invoice=(int)($data['invoice_id']??0);if($invoice<=0)throw new RuntimeException('Facture invalide.');if($action==='confirm_invoice'){$remaining=$this->remaining($invoice);if($amount<=0||$amount>$remaining||!self::date($date))throw new RuntimeException('Montant ou date d’encaissement invalide.');$this->db->beginTransaction();try{$this->db->prepare('INSERT INTO encaissements(facture_id,montant,date_encaissement,reference_paiement)VALUES(:invoice,:amount,:date,:reference)')->execute(['invoice'=>$invoice,'amount'=>$amount,'date'=>$date,'reference'=>trim((string)($data['reference']??''))]);$this->db->prepare('UPDATE factures_clients SET collection_tracking_status=:status,expected_collection_date=:date WHERE id=:id')->execute(['status'=>abs($remaining-$amount)<.01?'collected':'pending','date'=>$date,'id'=>$invoice]);$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}return;}$this->db->prepare('UPDATE factures_clients SET collection_tracking_status=:status,expected_collection_date=:date,collection_tracking_note=:note WHERE id=:id')->execute(['status'=>$action==='postpone_invoice'?'postponed':'cancelled','date'=>$action==='postpone_invoice'?$date:null,'note'=>trim((string)($data['note']??'')),'id'=>$invoice]);}
private function balances():array{$o=(float)$this->db->query('SELECT opening_balance FROM treasury_settings WHERE id=1')->fetchColumn();$p=(float)$this->db->query('SELECT COALESCE(SUM(montant),0) FROM encaissements')->fetchColumn();$m=$this->db->query("SELECT COALESCE(SUM(CASE WHEN movement_type='manual_entry' THEN amount ELSE 0 END),0)i,COALESCE(SUM(CASE WHEN movement_type='transfer_to_available' THEN amount WHEN movement_type='return_to_entries' THEN -amount ELSE 0 END),0)t,COALESCE(SUM(CASE WHEN movement_type='manual_out' THEN amount ELSE 0 END),0)o FROM treasury_ledger")->fetch();$d=(float)$this->db->query('SELECT COALESCE(SUM(montant),0) FROM decaissements')->fetchColumn();return['entries'=>$o+$p+(float)$m['i']-(float)$m['t'],'available'=>(float)$m['t']-(float)$m['o']-$d];}
private function remaining(int$id):float{$s=$this->db->prepare('SELECT montant_ttc-COALESCE((SELECT SUM(montant) FROM encaissements WHERE facture_id=f.id),0) FROM factures_clients f WHERE id=:id');$s->execute(['id'=>$id]);return(float)$s->fetchColumn();}private static function date(string$v):bool{$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return$d!==false&&$d->format('Y-m-d')===$v;}}
